name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.10.0
        with:
          push: true
