name: "Build Docker image"

on:
  push:

env:
  BASE_IMG: ghcr.io/${{ github.repository_owner }}/python-poetry

jobs:
  docker-build:
    name: Build Docker image (ghcr.io/murzindima/python-poetry) for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    environment:
      name: release
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false

      - uses: docker/setup-buildx-action@v3

      - name: Normalize Platform Pair (replace / with -)
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_TUPLE=${platform//\//-}" >> "$GITHUB_ENV"

      # Adapted from https://docs.docker.com/build/ci/github-actions/multi-platform/
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          cache-from: type=gha,scope=python-poetry-${{ env.PLATFORM_TUPLE }}
          cache-to: type=gha,mode=min,scope=python-poetry-${{ env.PLATFORM_TUPLE }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.BASE_IMG }}
          push: true
